Keppler-Admin/config/routes.rb
Rails.application.routes.draw do

  post 'newsletter/create', as: "newsletters"

  #blog
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  #catalog
  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'

  scope "(:locale)", :locale => /en|es/ do
    root to: 'frontend#index'
    resources :admin, only: :index
    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    scope :admin do
      resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :type_projects do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        resources :services do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
      end

      resources :planners, :except => [:new, :create] do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end

    #protfolio
    get 'projects/:catalog_permalink', to: "frontend#projects", as: "projects"
    get 'portfolio/:section', to: "frontend#portfolio_section", as: "portfolio_section"

    #briefing form
    get 'briefing', to: 'planners#briefing', as: :breafing
    post 'briefing', to: 'planners#create'
    post 'briefing/services/:type_project_id', to: 'planners#planner_services_json'
    post 'briefing/type_project/:type_project_id', to: 'planners#planner_type_project_json'

    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all

    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

    #contact_us
    mount KepplerContactUs::Engine, :at => '/', as: 'messages'
  end
end

Keppler-Admin/app/models/type_project.rb
#Generado por keppler
require 'elasticsearch/model'
class TypeProject < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :services, :dependent => :destroy
  has_many :planners
  validates_presence_of :name, :departament
  translates :name, :description

  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:name] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
      description:  self.description.to_s,
      departament: self.departament
    }.as_json
  end

end
#TypeProject.import

Keppler-Admin/app/controllers/type_projects_controller.rb
#Generado con Keppler.
class TypeProjectsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_type_project, only: [:show, :edit, :update, :destroy]

  # GET /type_projects
  def index
    type_projects = TypeProject.searching(@query).all
    @objects, @total = type_projects.page(@current_page), type_projects.size
    redirect_to type_projects_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /type_projects/1
  def show
  end

  # GET /type_projects/new
  def new
    @type_project = TypeProject.new
  end

  # GET /type_projects/1/edit
  def edit
  end

  # POST /type_projects
  def create
    @type_project = TypeProject.new(type_project_params)

    if @type_project.save
      redirect_to @type_project, notice: 'Type project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /type_projects/1
  def update
    if @type_project.update(type_project_params)
      redirect_to @type_project, notice: 'Type project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /type_projects/1
  def destroy
    @type_project.destroy
    redirect_to type_projects_url, notice: 'Type project was successfully destroyed.'
  end

  def destroy_multiple
    TypeProject.destroy redefine_ids(params[:multiple_ids])
    redirect_to type_projects_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_project
      @type_project = TypeProject.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def type_project_params
      params.require(:type_project).permit(:name, :description, :date_begin, :date_end, :budget, :machines, :persons, :departament)
    end
end

Keppler-Admin/app/views/type_projects/_description.html.haml
.listing-show-header
	%h5		
		= material_icon.md_24.assignment.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Keppler-Admin/app/views/type_projects/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to type_projects_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
			.pull-right
				= link_to "ES", es_link, class: "#{I18n.locale == :es ? ('locale active';) : ('locale';)}", "data-no-turbolink" => true
				| 
				= link_to "EN", en_link, class: "#{I18n.locale == :en ? ('locale active';) : ('locale';)}", "data-no-turbolink" => true
		.wrapper-inputs
			.card
				= simple_form_for @type_project do |f|
					.row
						= f.input :name
						= f.input :description, input_html: {class: "materialize-textarea"}
						= f.input :departament, label: false, collection: ["Slice Tur", "Slice Tech", "Slice Dev", "Slice Comunnity", "Slice Brand"],include_blank: "- Selecciona un slice -", input_html: { class: "browser-default" }
						= f.input :date_begin, label: "Fecha de inicio", as: :checkbox_material
						= f.input :date_end, label: "Fecha de culminación", as: :checkbox_material
						= f.input :budget, label: "Presupuesto", as: :checkbox_material
						= f.input :machines, label: "Numero de maquinas", as: :checkbox_material
						= f.input :persons, label: "Numero de personas", as: :checkbox_material


						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

Keppler-Admin/app/views/type_projects/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, TypeProject
			= link_to edit_type_project_path(@type_project), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.assignment.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @type_project.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @type_project.description
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

Keppler-Admin/app/views/type_projects/_listing.html.haml
%tr{ id: "row-#{type_project.id}" }
	- if can? :destroy_multiple, TypeProject
		%td.item-check{style:"width: 10%"}
			= link_to "", type_project_path(type_project), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{type_project.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{type_project.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{type_project.id}" }

		%td{style:"width: 5%"}
			= link_to "", type_project_path(type_project, search: @query), remote: true, class: "show-row"
			%span
				= material_icon.md_24.folder_open

		%td{style:"width: 84%"}
			= link_to "", type_project_path(type_project, search: @query), remote: true, class: "show-row"
			%span
				= type_project.name
								
	%td{style:"width: 1%"}
		= link_to "#", class: "btn-floating waves-effect waves-light btn-flat dropdown-button", "data-activates" => "catalog-options-#{type_project.id}" do
			= material_icon.md_24.more_vert.css_class("md-dark")
		%ul{ id: "catalog-options", class: "dropdown-content dropdow-content-listing", id: "catalog-options-#{type_project.id}"}
			%li
				= link_to 'Ver detallado', type_project_path(type_project)
			%li
				= link_to 'Ir a servicios', type_project_services_path(type_project)

Keppler-Admin/app/views/type_projects/edit.html.haml
= title "Tipo de Proyectos - editar | #{@type_project.id}"
= render 'form'

Keppler-Admin/app/views/type_projects/index.html.haml
= title("Tipo de Proyectos - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_type_project_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |type_project|
				= render 'listing', type_project: type_project
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado 
							= t("model.plural.#{controller_name}").downcase
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_type_project_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

Keppler-Admin/app/views/type_projects/new.html.haml
= title "Tipo de Proyectos - Nuevo"
= render 'form'

Keppler-Admin/app/views/type_projects/show.html.haml
= title "Tipo de Proyectos | #{@type_project.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, TypeProject
				= link_to type_project_path(@type_project), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, TypeProject
				= link_to edit_type_project_path(@type_project), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to type_projects_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @type_project.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= @type_project.description.to_s.humanize

Keppler-Admin/app/views/type_projects/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@type_project.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");